#!/bin/sh
# Navigate to the directory of this script (generally ~/.dotfiles/)
cd $(dirname $(readlink -f $0))

# The heavy lifting is done by an Emacs script
emacs -Q --script tangle-emacs-config.el

# Make sure any running Emacs instance gets updated settings
emacsclient -e '(load-file "~/.emacs.d/per-system-settings.el")' -a "echo 'Emacs is not currently running'"
